services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - CI=true
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "pnpm install && pnpm db:migrate && pnpm dev --host"
    tty: true
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - pnpm-store:/app/.pnpm-store

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=my-new-project
    ## Uncomment to expose the database port to the host
    # ports:
    #   - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d my-new-project"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  db-data:
  node_modules:
  pnpm-store:
